version: '3'

services:

  server:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./nginx/microservices.conf:/etc/nginx/conf.d/microservices.conf
      - ./site:/usr/share/nginx/site
      - ./service1:/usr/share/nginx/service1
      - ./service2:/usr/share/nginx/service2
    ports:
      - 80:80
      - 8081:8081
      - 8082:8082
      - 8080:8080

