version: '3'

services:

  server:
      image: nginx
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
        - ./site:/usr/share/nginx/site
      ports:
        - 80:80
        - 8080:8080

