version: '3'

services:

  server:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./nginx/microservices.conf:/etc/nginx/conf.d/microservices.conf
      - ./nginx/load-balancer.conf:/etc/nginx/conf.d/load-balancer.conf
      - ./nginx/fpm.conf:/etc/nginx/conf.d/fpm.conf
      - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./nginx/performance.conf:/etc/nginx/conf.d/performance.conf
      - ./site:/usr/share/nginx/site
      - ./service1:/usr/share/nginx/service1
      - ./service2:/usr/share/nginx/service2
      - ./performance:/usr/share/nginx/performance
      - ./logs:/var/log/nginx
    ports:
      - 80:80
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 8085:8085
      - 8086:8086

  fpm_server:
    image: php:fpm
    volumes:
      - ./fpm:/server
    ports:
      - 9000:9000

