version: '3'

services:

  server:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./nginx/microservices.conf:/etc/nginx/conf.d/microservices.conf
      - ./nginx/load-balancer.conf:/etc/nginx/conf.d/load-balancer.conf
      - ./nginx/fpm.conf:/etc/nginx/conf.d/fpm.conf
      - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./nginx/performance.conf:/etc/nginx/conf.d/performance.conf
      - ./site:/usr/share/nginx/site
      - ./service1:/usr/share/nginx/service1
      - ./service2:/usr/share/nginx/service2
      - ./performance:/usr/share/nginx/performance
      - ./logs:/var/log/nginx
      - ./tmp/cache:/tmp/cache
      - ./tmp/https:/tmp/https
    ports:
      - 80:80
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 8085:8085
      - 8086:8086
      - 443:443

  fpm_server:
    image: php:fpm
    volumes:
      - ./fpm:/server
    ports:
      - 9000:9000

  openssl:
    image: alpine/openssl
    command: req -x509 -nodes -days 30 -subj "/C=US/ST=NY/O=Company, Inc./CN=localhost" -addext "subjectAltName=DNS:mydomain.com" -newkey rsa:2048 -keyout /tmp/https/localhost.key -out /tmp/https/localhost.crt
    volumes:
      - ./tmp/https:/tmp/https
